### PR TITLE
Allow insecure TLS via CLI flag

### PR DESCRIPTION
**Pull request by mafrosis**
My company GHE instance uses a self-signed cert from our private CA..

### CODE REVIEW

**Comment by mafrosis** [comment]
Just pushed a couple of extra commits which are trivial logging changes in the same file. I didn't think it worth opening a separate P/R

**Review by tboerger — APPROVED** [review]

**Comment by tboerger** [comment]
Could you also add a changelog record to https://github.com/promhippie/github_exporter/tree/master/changelog/unreleased, please?

**Comment by mafrosis** [comment]
@tboerger Updated

**Comment by tboerger** [comment]
After finishing https://cloud.drone.io/promhippie/github_exporter/44 you could give the latest Docker tag a try, if everything behaves fine I will release v1.0.0.

**Pull request merged**
