### PR TITLE
feat: Add workflow run metrics

### PR DESCRIPTION
**Pull request by nikolaik**
WIP

### CODE REVIEW

**Comment by Amit-Baranes-Deel** [comment]
any update here? it would be amazing to have it from the exporter

**Comment by tboerger** [comment]
> any update here? it would be amazing to have it from the exporter

As you can see it's a draft. Maybe he just needs more time to get this finished.

**Comment by Amit-Baranes-Deel** [comment]
totally understand, thank you !

**Comment by nikolaik** [comment]
Superseded by https://github.com/promhippie/github_exporter/pull/405

**Pull request closed without merging**
