### PR TITLE
feat: integrate database and webhook handler

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
It's not entirely done as it requires some documentation :)

**Comment by luciano-buono** [comment]
Hi, is this version ready?
I see that the tags/releases haven't been updated yet

**Comment by tboerger** [comment]
Currently it's still only available via latest image tag. No release prepared yet.

**Comment by tboerger** [comment]
Finally there is a v3.0.1 release which should work without further issues :partying_face:

**Pull request merged**
